### Import Pandas Library

In [1]:
import pandas as pd

### Read Csv File

In [2]:
df=pd.read_csv('Task_1.csv')

### Show Csv

In [3]:
df.head()

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1

### Rename Multiple Columns

In [4]:
df=df.rename(columns={'Mat':'Matches','NO':'Not_Outs','HS':'Highest_Inns_Score','BF':'Balls_Faced','SR':'Batting_Strike_Rate'})

In [5]:
df.head()

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1

### Check Null Values

In [6]:
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                    True
Highest_Inns_Score     False
Ave                     True
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [7]:
df[df['Runs'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
12,JB Hobbs (ENG),1908-1930,61,102,7,NaN,211,NaN,5363+,46.22,15,28,4,276+,8
15,L Hutton (ENG),1937-1955,79,138,15,NaN,364,56.67,2844+,39.34,19,33,5,358+,7
19,HC Brook (ENG),2022-2026,35,60,2,NaN,317,54.79,3660,86.83,10,15,4,339,52

In [8]:
df[df['Ave'].isna()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
5,H Sutcliffe (ENG),1924-1935,54,84,9,4555.0,194,NaN,6558+,34.59,16,23,2,202+,6
12,JB Hobbs (ENG),1908-1930,61,102,7,NaN,211,NaN,5363+,46.22,15,28,4,276+,8

### Fill Null Values with 0

In [9]:
df['Runs']=df['Runs'].fillna(0)

In [10]:
df['Ave']=df['Ave'].fillna(0)

### Filled out successfully with 0

In [11]:
df[df['Player']=='JB Hobbs (ENG)']

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
12,JB Hobbs (ENG),1908-1930,61,102,7,0.0,211,0.0,5363+,46.22,15,28,4,276+,8

### No Null Values

In [12]:
df.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
Highest_Inns_Score     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

### Check Duplicates

In [13]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
63    False
64    False
65     True
66     True
67     True
Length: 68, dtype: bool

In [14]:
df[df['Player'].duplicated()==1]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
15,L Hutton (ENG),1937-1955,79,138,15,0.0,364,56.67,2844+,39.34,19,33,5,358+,7
26,SR Tendulkar (IND),1989-2013,200,329,33,15921.0,248*,53.78,29437+,54.04,51,68,14,2058+,69
31,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530.0,223,52.29,14372,52.39,24,33,11,957,51
65,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0
66,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0
67,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0

In [15]:
df[df['Player'].isin(['L Hutton (ENG)','SR Tendulkar (IND)','Mohammad Yousuf (PAK)','DR Jardine (ENG)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
14,L Hutton (ENG),1937-1955,79,138,15,6971.0,364,56.67,2844+,39.34,19,33,5,358+,7
15,L Hutton (ENG),1937-1955,79,138,15,0.0,364,56.67,2844+,39.34,19,33,5,358+,7
24,SR Tendulkar (IND),1989-2013,200,329,33,15921.0,248*,53.78,29437+,54.04,51,68,14,2058+,69
26,SR Tendulkar (IND),1989-2013,200,329,33,15921.0,248*,53.78,29437+,54.04,51,68,14,2058+,69
30,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530.0,223,52.29,14372,52.39,24,33,11,957,51
31,Mohammad Yousuf (PAK),1998-2010,90,156,12,7530.0,223,52.29,14372,52.39,24,33,11,957,51
64,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0
65,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0
66,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0
67,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0

In [16]:
df=df.drop_duplicates()

### Drop Duplicates

In [17]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
60    False
61    False
62    False
63    False
64    False
Length: 63, dtype: bool

### Split Columns

In [18]:
df['Span'].str.split(pat='-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
          ...
60    [2002, 2014]
61    [1924, 1934]
62    [1930, 1938]
63    [2018, 2025]
64    [1928, 1934]
Name: Span, Length: 63, dtype: object

In [19]:
df['Span'].str.split(pat='-').str[0]

0     1928
1     2022
2     2015
3     1963
4     1930
      ...
60    2002
61    1924
62    1930
63    2018
64    1928
Name: Span, Length: 63, dtype: object

In [20]:
df['Span'].str.split(pat='-').str[1]

0     1948
1     2025
2     2016
3     1970
4     1954
      ...
60    2014
61    1934
62    1938
63    2025
64    1934
Name: Span, Length: 63, dtype: object

In [21]:
df['Start_Year']=df['Span'].str.split(pat='-').str[0]

In [22]:
df['Final_Year']=df['Span'].str.split(pat='-').str[1]

In [23]:
df

,Player,Span,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),2022-2025,14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith (ICC/SA),2002-2014,117,205,13,9265.0,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
61,WH Ponsford (AUS),1924-1934,29,48,4,2122.0,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
62,SJ McCabe (AUS),1930-1938,39,62,5,2748.0,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
63,Hashmatullah Shahidi (AFG),2018-2025,11,21,5,771.0,246,48.18,1629,47.32,2,2,0,87,1,2018,2025
64,DR Jardine (ENG),1928-1934,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [24]:
df=df.drop(['Span'],axis=1)

In [25]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025
2,AC Voges (AUS),20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1,1930,1954

In [26]:
df['Player'].str.split(pat='(')

0               [DG Bradman , AUS)]
1               [PHKD Mendis , SL)]
2                 [AC Voges , AUS)]
3                [RG Pollock , SA)]
4                [GA Headley , WI)]
                  ...
60             [GC Smith , ICC/SA)]
61             [WH Ponsford , AUS)]
62               [SJ McCabe , AUS)]
63    [Hashmatullah Shahidi , AFG)]
64              [DR Jardine , ENG)]
Name: Player, Length: 63, dtype: object

In [27]:
df['Country']=df['Player'].str.split(pat='(').str[1]

In [28]:
df['Country']=df['Country'].str.split(pat=')').str[0]

In [29]:
df['Country']

0        AUS
1         SL
2        AUS
3         SA
4         WI
       ...
60    ICC/SA
61       AUS
62       AUS
63       AFG
64       ENG
Name: Country, Length: 63, dtype: object

In [30]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman (AUS),52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis (SL),14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges (AUS),20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock (SA),23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley (WI),22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,WI

In [31]:
df['Player']=df['Player'].str.split(pat='(').str[0]

In [32]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,WI

In [33]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score      object
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year              object
Final_Year              object
Country                 object
dtype: object

In [34]:
df['Highest_Inns_Score'].str.split(pat='*').str[0]

0     334
1     182
2     269
3     274
4     270
     ...
60    277
61    266
62    232
63    246
64    127
Name: Highest_Inns_Score, Length: 63, dtype: object

In [35]:
df['Highest_Inns_Score']=df['Highest_Inns_Score'].str.split(pat='*').str[0]

In [36]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416+,56,10,5,2,104+,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith,117,205,13,9265.0,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
61,WH Ponsford,29,48,4,2122.0,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS
62,SJ McCabe,39,62,5,2748.0,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS
63,Hashmatullah Shahidi,11,21,5,771.0,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,AFG
64,DR Jardine,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG

In [37]:
df['Highest_Inns_Score'].astype('int')

0     334
1     182
2     269
3     274
4     270
     ...
60    277
61    266
62    232
63    246
64    127
Name: Highest_Inns_Score, Length: 63, dtype: int64

In [38]:
df['Highest_Inns_Score']=df['Highest_Inns_Score'].astype('int')

In [39]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416+,56,10,5,2,104+,1,1930,1954,WI

In [40]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year              object
Final_Year              object
Country                 object
dtype: object

In [41]:
df=df.astype({'Start_Year':'int','Final_Year':'int'})

In [42]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [43]:
df['4s']=df['4s'].str.split(pat='+').str[0]

In [44]:
df['6s']=df['6s'].str.split(pat='+').str[0]

In [45]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416+,56,10,5,2,104,1,1930,1954,WI

In [46]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [47]:
df=df.astype({'4s':'int','6s':'int'})

In [48]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [49]:
df.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416+,56,10,5,2,104,1,1930,1954,WI

In [50]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [51]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800+,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707+,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416+,56,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith,117,205,13,9265.0,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
61,WH Ponsford,29,48,4,2122.0,266,48.22,3118+,44.77,7,6,1,119,0,1924,1934,AUS
62,SJ McCabe,39,62,5,2748.0,232,48.21,3217+,60.02,6,13,4,241,5,1930,1938,AUS
63,Hashmatullah Shahidi,11,21,5,771.0,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,AFG
64,DR Jardine,22,33,6,1296.0,127,48.00,2110+,25.59,1,10,2,53,0,1928,1934,ENG

In [52]:
df['Balls_Faced']=df['Balls_Faced'].str.split(pat='+').str[0]

In [53]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416,56,10,5,2,104,1,1930,1954,WI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,GC Smith,117,205,13,9265.0,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
61,WH Ponsford,29,48,4,2122.0,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
62,SJ McCabe,39,62,5,2748.0,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
63,Hashmatullah Shahidi,11,21,5,771.0,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,AFG
64,DR Jardine,22,33,6,1296.0,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [54]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [55]:
df['Balls_Faced']

0      9800
1      2063
2      2667
3      1707
4       416
      ...
60    15525
61     3118
62     3217
63     1629
64     2110
Name: Balls_Faced, Length: 63, dtype: object

In [56]:
df=df.drop(8,axis=0)

In [57]:
df=df.drop(13,axis=0)

In [58]:
df=df.drop(56,axis=0)

In [59]:
df['Balls_Faced']

0      9800
1      2063
2      2667
3      1707
4       416
5      6558
6      1288
7      4957
9      7491
10     4063
11    22882
12     5363
14     2844
15     2844
16    19966
17    28903
18      178
19     3660
20    18198
21      665
22     1823
23    13079
24    29437
25      108
27    19753
28    15164
29    31258
30    14372
32    19375
33    22782
34     2035
35    10636
36    12436
37    27395
38    14184
39    24242
40    22461
41    14349
42    16077
43    27002
44     9613
45     2731
46    22959
47    16345
48      488
49      619
50    10441
51     3803
52     2445
53    15456
54      885
55      158
57    11641
58     1799
59     8662
60    15525
61     3118
62     3217
63     1629
64     2110
Name: Balls_Faced, dtype: object

In [60]:
df['Balls_Faced']=df['Balls_Faced'].astype('int')

In [61]:
df

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Start_Year,Final_Year,Country
0,DG Bradman,52,80,10,6996.0,334,99.94,9800,58.6,29,13,7,626,6,1928,1948,AUS
1,PHKD Mendis,14,24,3,1316.0,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL
2,AC Voges,20,31,7,1485.0,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS
3,RG Pollock,23,41,4,2256.0,274,60.97,1707,54.48,7,11,1,246,11,1963,1970,SA
4,GA Headley,22,40,4,2190.0,270,60.83,416,56,10,5,2,104,1,1930,1954,WI
5,H Sutcliffe,54,84,9,4555.0,194,0.00,6558,34.59,16,23,2,202,6,1924,1935,ENG
6,E Paynter,20,31,5,1540.0,243,59.23,1288,45.88,4,7,3,125,4,1931,1939,ENG
7,KF Barrington,82,131,15,6806.0,256,58.67,4957,42.42,20,35,5,591,27,1955,1968,ENG
9,WR Hammond,85,140,16,7249.0,336,58.45,7491,38.07,22,24,4,419,27,1927,1947,ENG
10,GS Sobers,93,160,21,8032.0,365,57.78,4063,53.58,26,30,12,593,32,1954,1974,WI
11,KC Sangakkara,134,233,17,12400.0,319,57.40,22882,54.19,38,52,11,1491,51,2000,2015,SL
12,JB Hobbs,61,102,7,0.0,211,0.00,5363,46.22,15,28,4,276,8,1908,1930,ENG
14,L Hutton,79,138,15,6971.0,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG
15,L Hutton,79,138,15,0.0,364,56.67,2844,39.34,19,33,5,358,7,1937,1955,ENG
16,SPD Smith,123,220,28,10763.0,239,56.05,19966,53.9,37,44,11,1172,67,2010,2026,AUS
17,JH Kallis,166,280,40,13289.0,224,55.37,28903,45.97,45,58,16,1488,97,1995,2013,ICC/SA
18,GE Tyldesley,14,20,2,990.0,122,55.00,178,29.21,3,6,2,37,2,1921,1929,ENG
19,HC Brook,35,60,2,0.0,317,54.79,3660,86.83,10,15,4,339,52,2022,2026,ENG
20,KS Williamson,108,192,19,9461.0,251,54.68,18198,51.98,33,38,11,1056,28,2010,2025,NZ
21,CA Davis,15,29,5,1301.0,183,54.20,665,35.48,4,4,1,65,1,1968,1973,WI
22,VG Kambli,17,21,1,1084.0,227,54.20,1823,59.46,4,3,3,124,6,1993,1995,IND
23,GS Chappell,87,151,19,7110.0,247,53.86,13079,51.53,24,31,12,755,16,1970,1984,AUS
24,SR Tendulkar,200,329,33,15921.0,248,53.78,29437,54.04,51,68,14,2058,69,1989,2013,IND
25,AD Nourse,34,62,7,2960.0,231,53.81,108,63.88,9,14,3,115,6,1935,1951,SA
27,BC Lara,131,232,6,11953.0,400,52.88,19753,60.51,34,48,17,1559,88,1990,2006,ICC/WI
28,Javed Miandad,124,189,21,8832.0,280,52.57,15164,45.99,23,43,6,788,48,1976,1993,PAK
29,R Dravid,164,286,32,13288.0,270,52.31,31258,42.51,36,63,8,1654,21,1996,2012,ICC/IND
30,Mohammad Yousuf,90,156,12,7530.0,223,52.29,14372,52.39,24,33,11,957,51,1998,2010,PAK
32,Younis Khan,118,213,19,10099.0,313,52.05,19375,52.12,34,33,19,1082,70,2000,2017,PAK
33,RT Ponting,168,287,29,13378.0,257,51.85,22782,58.72,41,62,17,1509,73,1995,2012,AUS
34,J Ryder,20,32,5,1394.0,201,51.62,2035,44.86,3,9,1,102,3,1920,1929,AUS
35,A Flower,63,112,19,4794.0,232,51.54,10636,45.07,12,27,5,543,20,1992,2002,ZIM
36,MEK Hussey,79,137,16,6235.0,195,51.52,12436,50.13,19,29,12,685,39,2005,2013,AUS
37,S Chanderpaul,164,280,49,11867.0,203,51.37,27395,43.31,30,66,15,1285,36,1994,2015,WI
38,SM Gavaskar,125,214,16,10122.0,236,51.12,14184,43.35,34,45,12,908,26,1971,1987,IND
39,JE Root,163,298,25,13943.0,262,51.07,24242,57.51,41,66,15,1492,46,2012,2026,ENG
40,SR Waugh,168,260,46,10927.0,200,51.06,22461,48.64,32,50,22,1175,20,1985,2004,AUS
41,ML Hayden,103,184,14,8625.0,380,50.73,14349,60.1,30,29,14,1049,82,1994,2009,AUS
42,AB de Villiers,114,191,18,8765.0,278,50.66,16077,54.51,22,46,8,1024,64,2004,2018,SA
43,AR Border,156,265,44,11174.0,205,50.56,27002,41.09,27,63,11,1161,28,1978,1994,AUS
44,IVA Richards,121,182,12,8540.0,291,50.23,9613,69.77,24,45,10,952,84,1974,1991,WI
45,DCS Compton,78,131,15,5807.0,278,50.06,2731,38.81,17,28,10,342,3,1937,1957,ENG
46,DPMD Jayawardene,149,252,15,11814.0,374,49.84,22959,51.45,34,50,15,1387,61,1997,2014,SL
47,Inzamam-ul-Haq,120,200,22,8830.0,329,49.60,16345,54.02,25,46,15,1105,48,1992,2007,ICC/PAK
48,FMM Worrell,51,87,9,3860.0,261,49.48,488,40.16,9,22,11,240,11,1948,1963,WI
49,CP Mead,17,26,2,1185.0,182,49.37,619,30.04,4,3,3,38,0,1911,1928,ENG
50,V Sehwag,104,180,6,8586.0,319,49.34,10441,82.23,23,32,16,1233,91,2001,2013,ICC/IND
51,YBK Jaiswal,28,53,2,2511.0,214,49.23,3803,66.02,7,13,6,312,45,2023,2025,IND
52,Abid Ali,16,26,2,1180.0,215,49.16,2445,48.26,4,3,2,148,5,2019,2021,PAK
53,MJ Clarke,115,198,22,8643.0,329,49.10,15456,55.92,28,27,9,978,39,2004,2015,AUS
54,KC Bland,21,39,5,1669.0,144,49.08,885,37.74,3,9,2,123,20,1961,1966,SA
55,B Mitchell,42,80,9,3471.0,189,48.88,158,29.11,8,21,3,41,1,1929,1949,SA
57,TT Samaraweera,81,132,20,5462.0,231,48.76,11641,46.92,14,30,11,633,7,2001,2013,SL
58,RN Harvey,79,137,10,6149.0,205,48.41,1799,43.74,21,24,7,427,1,1948,1963,AUS
59,KD Walters,74,125,14,5357.0,250,48.26,8662,49.16,15,33,4,525,23,1965,1981,AUS
60,GC Smith,117,205,13,9265.0,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA
61,WH Ponsford,29,48,4,2122.0,266,48.22,3118,44.77,7,6,1,119,0,1924,1934,AUS
62,SJ McCabe,39,62,5,2748.0,232,48.21,3217,60.02,6,13,4,241,5,1930,1938,AUS
63,Hashmatullah Shahidi,11,21,5,771.0,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,AFG
64,DR Jardine,22,33,6,1296.0,127,48.00,2110,25.59,1,10,2,53,0,1928,1934,ENG

In [62]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object

In [63]:
df['Batting_Strike_Rate']=df['Batting_Strike_Rate'].astype('float')

### Data Types Handling Successfully

In [66]:
df.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                   float64
Highest_Inns_Score       int64
Ave                    float64
Balls_Faced              int64
Batting_Strike_Rate    float64
100                      int64
50                       int64
0                        int64
4s                       int64
6s                       int64
Start_Year               int64
Final_Year               int64
Country                 object
dtype: object